services:
  signup_service:
    container_name: signup_service
    build:
      context: signup
    env_file:
      - signup/.env
    command: >
      sh -c "
      echo signup_service is ready to fly!;
      yarn start:dev
      "
    ports:
      - "${SIGNUP_PORT}:3000"
    volumes:
      - ./signup/src:/app/src
      - ./signup/test:/app/test
    depends_on:
      - signup_db

  notifications_service:
    container_name: notifications_service
    build:
      context: notifications
    env_file:
      - notifications/.env
    command: >
      sh -c "
      echo notifications_service is ready to fly!;
      yarn start:dev
      "
    ports:
      - "${NOTIFICATIONS_PORT}:3000"
    volumes:
      - ./notifications/src:/app/src
      - ./notifications/test:/app/test

  signup_db:
    container_name: signup_db
    image: postgres:16
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./signup/signup_db:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  signup_db:
